### ISSUE TITLE
Question: the output format in the supplementary 

### ISSUE THREAD

**Issue by alimayy** [carolzhou/multiPhATE#12]
Dear developers,

Thank you very much for developing this pipeline. I was wondering if there is a script that you can provide that we can use for converting the main multiPhATE output to what you have in the [supplementary folder](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/35/21/10.1093_bioinformatics_btz258/1/btz258_supplementary_data.zip?Expires=1579591473&Signature=jqeYAHb4NJmHdVNkxHM-1ZHQE0nfPm1vLcSfhCBhgUV-rl5RahT-nTZPkR5zuRmLMBOjdeMbwayD28jMGAAedhJPUAZTLCkHnXXgzgNbRSgav6Y1r3AaBoG1TcenAm4v64E1cA9fmhWPdivlmqA2~W3kVG20IPoOKddTTFGPqjucVnXTNubVUGB~rG~vMZXH0Xqaecqpx132C2fHRTyGi03NFqheST4n4a~VcXKYE8X3EgkPQD-wYRL60zJ4G52wvUImjJrY7hBgFlMuVDJGF8yI2XAc11KPj4RXrIPiCdD94jMLlxzGhBru8HoDqgIgXqEN2r0ZszIWX4RicxoijQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA), especially the PDF files, for formatting purposes

phate_P2_CGC.pdf
phate_genome_annotations.pdf

Thanks in advance for letting me know,
Ali

**Comment by carolzhou** [comment]
The P2_CGC.pdf file is a pdf version of the PhATE output in file CGC_results.txt (see PipelineOutput folder in the sub directory for your genome). Of course you might need to adjust font sizes and change to landscape orientation before saving in pdf format, in order to fit each data line on a single line of printed text.

The phate_genome_annotations data were created manually in a spreadsheet by examining the totality of the PhATE annotation output and interpreting those results to assign summary functional annotations per gene, and identifying the closest P2 homologs as in the Christie 2016 paper.

I hope that helps.



Sent from my iPhone

On Dec 17, 2019, at 7:52 AM, alimayy <notifications@github.com> wrote:

﻿

Dear developers,

Thank you very much for developing this pipeline. I was wondering if there is a script that you can provide that we can use for converting the main multiPhATE output to what you have in the supplementary folder<https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/35/21/10.1093_bioinformatics_btz258/1/btz258_supplementary_data.zip?Expires=1579591473&Signature=jqeYAHb4NJmHdVNkxHM-1ZHQE0nfPm1vLcSfhCBhgUV-rl5RahT-nTZPkR5zuRmLMBOjdeMbwayD28jMGAAedhJPUAZTLCkHnXXgzgNbRSgav6Y1r3AaBoG1TcenAm4v64E1cA9fmhWPdivlmqA2~W3kVG20IPoOKddTTFGPqjucVnXTNubVUGB~rG~vMZXH0Xqaecqpx132C2fHRTyGi03NFqheST4n4a~VcXKYE8X3EgkPQD-wYRL60zJ4G52wvUImjJrY7hBgFlMuVDJGF8yI2XAc11KPj4RXrIPiCdD94jMLlxzGhBru8HoDqgIgXqEN2r0ZszIWX4RicxoijQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA>, especially the PDF files, for formatting purposes

phate_P2_CGC.pdf
phate_genome_annotations.pdf

Thanks in advance for letting me know,
Ali

**Comment by alimayy** [comment]
Thanks a lot for your quick response Carol, this certainly helps!
